const INVALID_ERROR_CODE = 400;
const UNAUTHORIZED_CODE = 401;
const NOT_FOUND_CODE = 404;
const CONFLICT_ERROR = 409;
const ERROR_CODE = 500;
const CREATED_CODE = 201;
const MONGO_DUPLICATE_ERROR_CODE = 11000;

module.exports = {
  INVALID_ERROR_CODE,
  UNAUTHORIZED_CODE,
  NOT_FOUND_CODE,
  CONFLICT_ERROR,
  ERROR_CODE,
  CREATED_CODE,
  MONGO_DUPLICATE_ERROR_CODE,
};
